services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: ecg_classifier
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  data-init:
    build:
      context: ..
      dockerfile: infra/Dockerfile.data
    env_file:
      - ../.env
    command: /app/scripts/data_init.sh
    volumes:
      - ..:/app
      - shared_data:/shared-data
    working_dir: /app

  api:
    image: ecg-classifier-app:latest
    build:
      context: ..
      dockerfile: infra/Dockerfile.app
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000
    env_file:
      - ../.env
    depends_on:
      - postgres
      - redis
      - data-init
    ports:
      - "8000:8000"
    volumes:
      - ..:/app
      - shared_data:/shared-data
    working_dir: /app

  worker-gpu:
    image: ecg-classifier-app:latest
    build:
      context: ..
      dockerfile: infra/Dockerfile.app
    command: celery -A api.celery_app:celery_app worker --loglevel=info --hostname=worker-gpu@%h --queues=train,infer_gpu --pool=solo --concurrency=1
    environment:
        PROMETHEUS_WORKER_SERVER_ENABLED: "true"
        PROMETHEUS_WORKER_METRICS_PORT: "9101"
    env_file:
      - ../.env
    depends_on:
      - postgres
      - redis
      - data-init
    volumes:
      - ..:/app
      - shared_data:/shared-data
    working_dir: /app
    ports:
      - "9101:9101"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

  worker-cpu:
    image: ecg-classifier-app:latest
    build:
      context: ..
      dockerfile: infra/Dockerfile.app
    command: celery -A api.celery_app:celery_app worker --loglevel=info --hostname=worker-cpu@%h --queues=infer_cpu --pool=solo --concurrency=1
    environment:
      PROMETHEUS_WORKER_SERVER_ENABLED: "true"
      PROMETHEUS_WORKER_METRICS_PORT: "9102"
    env_file:
      - ../.env
    depends_on:
      - postgres
      - redis
      - data-init
    volumes:
      - ..:/app
      - shared_data:/shared-data
    working_dir: /app
    ports:
      - "9102:9102"

  telegram-bot:
    image: ecg-classifier-app:latest
    build:
      context: ..
      dockerfile: infra/Dockerfile.app
    command: python -m tg_bot.main
    env_file:
      - ../.env
    depends_on:
      - api
      - postgres
      - redis
    volumes:
      - ..:/app
      - shared_data:/shared-data
    working_dir: /app

  flower:
    image: mher/flower
    command: >
      celery --broker=${CELERY_BROKER_URL} flower
      --port=${FLOWER_PORT}
      --basic_auth=${FLOWER_BASIC_AUTH}
    env_file:
      - ../.env
    depends_on:
      - redis
    ports:
      - "5555:5555"

  prometheus:
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - api
      - worker-gpu
      - worker-cpu

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
    depends_on:
      - prometheus

volumes:
  shared_data:
  grafana_data: