FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y \
    curl \
    p7zip-full \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir gdown==5.2.0

WORKDIR /app

COPY infra/k8s/scripts/k8s_data_init.py /app/k8s_data_init.py

CMD ["python", "/app/k8s_data_init.py"]