"""add tg

Revision ID: c7af02ed1de7
Revises: 20260414_000001
Create Date: 2026-04-15 02:26:47.081220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'c7af02ed1de7'
down_revision: Union[str, None] = '20260414_000001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_users',
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('resolved_login', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('telegram_user_id')
    )
    op.create_index(op.f('ix_telegram_users_resolved_login'), 'telegram_users', ['resolved_login'], unique=False)
    op.create_table('telegram_inference_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.String(length=255), nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('image_path', sa.Text(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('queue_name', sa.String(length=64), nullable=True),
    sa.Column('model_key', sa.String(length=128), nullable=True),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('predicted_class', sa.String(length=64), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('probabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['telegram_user_id'], ['telegram_users.telegram_user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegram_inference_history_created_at'), 'telegram_inference_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_telegram_inference_history_status'), 'telegram_inference_history', ['status'], unique=False)
    op.create_index(op.f('ix_telegram_inference_history_task_id'), 'telegram_inference_history', ['task_id'], unique=True)
    op.create_index(op.f('ix_telegram_inference_history_telegram_user_id'), 'telegram_inference_history', ['telegram_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telegram_inference_history_telegram_user_id'), table_name='telegram_inference_history')
    op.drop_index(op.f('ix_telegram_inference_history_task_id'), table_name='telegram_inference_history')
    op.drop_index(op.f('ix_telegram_inference_history_status'), table_name='telegram_inference_history')
    op.drop_index(op.f('ix_telegram_inference_history_created_at'), table_name='telegram_inference_history')
    op.drop_table('telegram_inference_history')
    op.drop_index(op.f('ix_telegram_users_resolved_login'), table_name='telegram_users')
    op.drop_table('telegram_users')
    # ### end Alembic commands ###