apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - pvc.yaml
  - postgres.yaml
  - redis.yaml
  - minio.yaml
  - minio-init-job.yaml
  - mlflow.yaml
  - data-init-job.yaml
  - api.yaml
  - worker-gpu.yaml
  - worker-cpu.yaml
  - telegram-bot.yaml
  - flower.yaml
  - prometheus.yaml
  - grafana.yaml