apiVersion: batch/v1
kind: Job
metadata:
  name: minio-init
  namespace: ecg-classifier
spec:
  backoffLimit: 5
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: minio-init
          image: quay.io/minio/mc:latest
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: ecg-secret
                  key: MINIO_ROOT_USER
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ecg-secret
                  key: MINIO_ROOT_PASSWORD
          command:
            - /bin/sh
            - -c
            - |
              echo "Waiting for MinIO..."

              for i in $(seq 1 60); do
                mc alias set local http://minio:9000 "$MINIO_ROOT_USER" "$MINIO_ROOT_PASSWORD" && break
                echo "MinIO is not ready yet..."
                sleep 2
              done

              mc mb -p local/mlflow || true
              mc mb -p local/dvc || true
              mc ls local

              echo "MinIO buckets ensured."