apiVersion: v1
kind: Secret
metadata:
  name: ecg-secret
  namespace: ecg-classifier
type: Opaque
stringData:
  # Auth
  JWT_SECRET_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0.KMUFsIDTnFmyG3nMiGM6H9FNFUROf3wh7SmqJp-QV30"
  JWT_ALGORITHM: "HS256"
  ACCESS_TOKEN_EXPIRE_MINUTES: "600"
  ADMIN_USERNAME: "admin"
  ADMIN_PASSWORD: "777"

  # Database
  POSTGRES_DB: "ecg_classifier"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  DATABASE_URL: "postgresql+psycopg://postgres:postgres@postgres:5432/ecg_classifier"

  # MinIO / S3
  MINIO_ROOT_USER: "minio"
  MINIO_ROOT_PASSWORD: "minio123"
  AWS_ACCESS_KEY_ID: "minio"
  AWS_SECRET_ACCESS_KEY: "minio123"

  # Flower auth
  FLOWER_BASIC_AUTH: "admin:admin"

  # Telegram
  TG_BOT_TOKEN: "8035555451:AAErbTLBLEAe-jpb0E73QLgIK6CqlAKQ5mM"

  # Google Drive
  GDRIVE_PTBXL_ARCHIVE_URL: "https://drive.google.com/file/d/1yrImBEK5sOscq_Bp9M7TeuIPYd3ULtbx/view?usp=sharing"
  GDRIVE_ECG_IMG_ARCHIVE_URL: "https://drive.google.com/file/d/1sDtpIgmpANa5W38QWDObzMmsH1aVv8we/view?usp=sharing"