apiVersion: v1
kind: Secret
metadata:
  name: ecg-secret
  namespace: ecg-classifier
type: Opaque
stringData:
  JWT_SECRET_KEY: "<YOUR SECRET KEY>"
  JWT_ALGORITHM: "HS256"
  ACCESS_TOKEN_EXPIRE_MINUTES: "600"

  ADMIN_USERNAME: "<YOUR ADMIN USER>"
  ADMIN_PASSWORD: "<YOUR ADMIN PASSWORD>"

  DATABASE_URL: "postgresql+psycopg://postgres:<CHANGE_ME>@postgres:5432/ecg_classifier"

  POSTGRES_DB: "ecg_classifier"
  POSTGRES_USER: "<YOUR POSTGRES USER>"
  POSTGRES_PASSWORD: "<YOUR POSTGRES PASSWORD>"

  MINIO_ROOT_USER: "<YOUR MINIO USER>"
  MINIO_ROOT_PASSWORD: "<YOUR MINIO PASSWORD>"

  AWS_ACCESS_KEY_ID: "<YOUR MINIO USER>"
  AWS_SECRET_ACCESS_KEY: "<YOUR MINIO PASSWORD>"

  FLOWER_BASIC_AUTH: "<YOUR FLOWER USER>:<YOUR FLOWER PASSWORD>"

  TG_BOT_TOKEN: "<TELEGRAM BOT TOKEN>"

  GDRIVE_PTBXL_ARCHIVE_URL: "https://drive.google.com/file/d/1yrImBEK5sOscq_Bp9M7TeuIPYd3ULtbx/view?usp=sharing"
  GDRIVE_ECG_IMG_ARCHIVE_URL: "https://drive.google.com/file/d/1sDtpIgmpANa5W38QWDObzMmsH1aVv8we/view?usp=sharing"