apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-cpu
  namespace: ecg-classifier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-cpu
  template:
    metadata:
      labels:
        app: worker-cpu
    spec:
      initContainers:
        - name: wait-data
          image: busybox:1.36
          command:
            - /bin/sh
            - -c
            - |
              until [ -f /shared-data/ecg_img/.extracted ] && [ -f /shared-data/PTB-XL/.extracted ]; do
                echo "Waiting for data-init..."
                sleep 5
              done
          volumeMounts:
            - name: shared-data
              mountPath: /shared-data
      containers:
        - name: worker-cpu
          image: ecg-classifier-app:latest
          imagePullPolicy: IfNotPresent
          command:
            - celery
            - -A
            - api.celery_app:celery_app
            - worker
            - --loglevel=info
            - --hostname=worker-cpu@%h
            - --queues=infer_cpu
            - --pool=solo
            - --concurrency=1
            - --events
          ports:
            - name: metrics
              containerPort: 9102
          envFrom:
            - configMapRef:
                name: ecg-config
            - secretRef:
                name: ecg-secret
          env:
            - name: PROMETHEUS_WORKER_SERVER_ENABLED
              value: "true"
            - name: PROMETHEUS_WORKER_METRICS_PORT
              value: "9102"
            - name: INFERENCE_DEVICE
              value: "cpu"
            - name: CUDA_VISIBLE_DEVICES
              value: ""
          volumeMounts:
            - name: shared-data
              mountPath: /shared-data
      volumes:
        - name: shared-data
          persistentVolumeClaim:
            claimName: shared-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: worker-cpu
  namespace: ecg-classifier
spec:
  selector:
    app: worker-cpu
  ports:
    - name: metrics
      port: 9102
      targetPort: 9102